print("Atha Nala Isra Raditya - 3202216006 - TI 1A - \npraktikum algoritma pemrograman - variabel dan tipe data")
print(False)
print("<class 'bool'>")
print(100)
print(1.0e-3)
print('bilangan desimal dari 0x01 adalah', 0.01)
print(10)
print("<class 'comlex'>")
print(2+6j)
print("<class 'complex'>")
print([96, 97, 98, 100])
print(["seratus", "dua ratus", "tiga ratus",])
string = {'nama': 'Atha', 'umur': 18}
print(string)
type(string)
print('string contains a single quote (\') character.')