import datetime
import modul_bangun_ruang

print(modul_bangun_ruang.__file__)
print('Tanggal dan waktu sekarang : ',datetime.datetime.now())
print()
print('PI : ',modul_bangun_ruang.PI)
print()
print('Luas kubus : ',modul_bangun_ruang.luas_kubus(sisi=30))
print('Keliling kubus : ',modul_bangun_ruang.keliling_kubus(rusuk=6))
print()
print('Luas balok : ',modul_bangun_ruang.luas_balok(panjang=5,lebar=8,tinggi=10))
print('Keliling balok : ',modul_bangun_ruang.keliling_balok(panjang=5,lebar=8,tinggi=10))
print()
print('Luas limas segiempat : ',modul_bangun_ruang.luas_limas_segiempat(luas_alas=20,luas_sisi_tegak=10))
print('Volume limas segiempat : ',modul_bangun_ruang.volume_limas_segiempat(luas_alas=32,tinggi=25))
print()
print('Luas limas segitiga : ',modul_bangun_ruang.luas_limas_segitiga(luas_alas=15,luas_selubung=17))
print('Volume limas segitiga : ',modul_bangun_ruang.volume_limas_segitiga(luas_alas=30,tinggi=22))
print()
print('Luas prisma : ',modul_bangun_ruang.luas_prisma(luas_alas=15,luas_tutup=12,luas_selimut=20))
print('Volume prisma : ',modul_bangun_ruang.volume_prisma(luas_alas=19,tinggi=24))
print()
print('Luas tabung : ',modul_bangun_ruang.luas_tabung(luas_alas=11,luas_selimut_tabung=20))
print('Volume tabung : ',modul_bangun_ruang.volume_tabung(radius=15,tinggi=27))
print()
print('luas kerucut : ',modul_bangun_ruang.luas_kerucut(luas_alas=30,luas_selimut=31))
print('Volume kerucut : ',modul_bangun_ruang.volume_kerucut(radius=20,tinggi=27))
print()
print('Luas bola : ',modul_bangun_ruang.luas_bola(radius=25))
print('Volume bola : ',modul_bangun_ruang.volume_bola(radius=36))