PROGRAM tabel;
USES CRT;
BEGIN;
      CLRSCR;
      WRITELN('зддддбддддддддддддбддддддд©');
      WRITELN('Ё NO Ё    NIM     Ё NAMA  Ё');
      WRITELN('цддддеддддддддддддеддддддд╢');
      WRITELN('Ё 1  Ё 3200916001 Ё Budi  Ё');
      WRITELN('Ё 2  Ё 3200916002 Ё Antok Ё');
      WRITELN('Ё 3  Ё 3200916003 Ё Siska Ё');
      WRITELN('юддддаддддддддддддаддддддды');
      READLN;
END.

